CREATE TABLE IF NOT EXISTS "finderfo_developer_profiles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finderfo_developer_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"skills" text[] NOT NULL,
	"experience_level" varchar(50) NOT NULL,
	"github_link" text NOT NULL,
	"portfolio_links" text,
	"availability" varchar(50) NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "finderfo_developer_profiles" ADD CONSTRAINT "finderfo_developer_profiles_created_by_finderfo_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."finderfo_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
