CREATE TABLE IF NOT EXISTS "finderfo_founder_profiles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finderfo_founder_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"startup_name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"stage" varchar(50) NOT NULL,
	"requirements" text NOT NULL,
	"budget" varchar(50) NOT NULL,
	"pitch_deck" varchar(50),
	"created_by_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "finderfo_founder_profiles" ADD CONSTRAINT "finderfo_founder_profiles_created_by_id_finderfo_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."finderfo_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "startup_name_idx" ON "finderfo_founder_profiles" USING btree ("startup_name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "created_by_id_idx" ON "finderfo_founder_profiles" USING btree ("created_by_id");