CREATE TABLE IF NOT EXISTS "finderfo_applications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finderfo_applications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" varchar(255) NOT NULL,
	"developer_id" varchar(255) NOT NULL,
	"cover_letter" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "finderfo_founder_profiles" ALTER COLUMN "pitch_deck" SET NOT NULL;